sonar.projectKey=seminario_front
sonar.organization=Miguel Montes
sonar.host.url=https://sonarcloud.io
sonar.token=22f9b9ce07fe1cb5ff9b852a18ee693743945ef8

# Rutas del código
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/environments/**

# Cobertura de tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info